# ------------------------------------------------------------------------------
#
#   Copyright 2023
#   Copyright 2023 valory-xyz
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# ------------------------------------------------------------------------------

"""This package contains a behaviour that autogenerated from the protocol ``."""

import os
from abc import ABC
from enum import Enum
from typing import Any

from aea.skills.behaviours import State, FSMBehaviour


class Taraxa0abciappEvents(Enum):
    """Events for the fsm."""

    DONE = "DONE"


class Taraxa0abciappStates(Enum):
    """States for the fsm."""

    SMARTCONTRACTCREATIONROUND = "smartcontractcreationround"
    FINISHEDROUND = "finishedround"
    TRENDDETECTIONROUND = "trenddetectionround"
    MEMECOINPERSONACREATIONROUND = "memecoinpersonacreationround"
    TOKENOMICSCONFIGURATIONROUND = "tokenomicsconfigurationround"
    DEPLOYMENTROUND = "deploymentround"


class BaseState(State, ABC):
    """Base class for states."""

    _state: Taraxa0abciappStates = None

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._event = None
        self._is_done = False  # Initially, the state is not done

    def act(self) -> None:
        """Perform the act."""
        self._is_done = True
        self._event = Taraxa0abciappEvents.DONE

    def is_done(self) -> bool:
        """Is done."""
        return self._is_done

    @property
    def event(self) -> str | None:
        """Current event."""
        return self._event


# Define states


class SmartContractCreationRound(BaseState):
    """This class implements the behaviour of the state SmartContractCreationRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Taraxa0abciappStates.SMARTCONTRACTCREATIONROUND


class FinishedRound(BaseState):
    """This class implements the behaviour of the state FinishedRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Taraxa0abciappStates.FINISHEDROUND


class TrendDetectionRound(BaseState):
    """This class implements the behaviour of the state TrendDetectionRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Taraxa0abciappStates.TRENDDETECTIONROUND


class MemecoinPersonaCreationRound(BaseState):
    """This class implements the behaviour of the state MemecoinPersonaCreationRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Taraxa0abciappStates.MEMECOINPERSONACREATIONROUND


class TokenomicsConfigurationRound(BaseState):
    """This class implements the behaviour of the state TokenomicsConfigurationRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Taraxa0abciappStates.TOKENOMICSCONFIGURATIONROUND


class DeploymentRound(BaseState):
    """This class implements the behaviour of the state DeploymentRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Taraxa0abciappStates.DEPLOYMENTROUND


class Taraxa0abciappFsmBehaviour(FSMBehaviour):
    """This class implements a simple Finite State Machine behaviour."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.register_state(Taraxa0abciappStates.TRENDDETECTIONROUND.value, TrendDetectionRound(**kwargs), True)

        self.register_state(Taraxa0abciappStates.FINISHEDROUND.value, FinishedRound(**kwargs))

        self.register_state(Taraxa0abciappStates.SMARTCONTRACTCREATIONROUND.value, SmartContractCreationRound(**kwargs))
        self.register_state(
            Taraxa0abciappStates.MEMECOINPERSONACREATIONROUND.value, MemecoinPersonaCreationRound(**kwargs)
        )
        self.register_state(
            Taraxa0abciappStates.TOKENOMICSCONFIGURATIONROUND.value, TokenomicsConfigurationRound(**kwargs)
        )
        self.register_state(Taraxa0abciappStates.DEPLOYMENTROUND.value, DeploymentRound(**kwargs))

        self.register_transition(
            source=Taraxa0abciappStates.DEPLOYMENTROUND.value,
            event=Taraxa0abciappEvents.DONE,
            destination=Taraxa0abciappStates.FINISHEDROUND.value,
        )
        self.register_transition(
            source=Taraxa0abciappStates.MEMECOINPERSONACREATIONROUND.value,
            event=Taraxa0abciappEvents.DONE,
            destination=Taraxa0abciappStates.SMARTCONTRACTCREATIONROUND.value,
        )
        self.register_transition(
            source=Taraxa0abciappStates.SMARTCONTRACTCREATIONROUND.value,
            event=Taraxa0abciappEvents.DONE,
            destination=Taraxa0abciappStates.TOKENOMICSCONFIGURATIONROUND.value,
        )
        self.register_transition(
            source=Taraxa0abciappStates.TOKENOMICSCONFIGURATIONROUND.value,
            event=Taraxa0abciappEvents.DONE,
            destination=Taraxa0abciappStates.DEPLOYMENTROUND.value,
        )
        self.register_transition(
            source=Taraxa0abciappStates.TRENDDETECTIONROUND.value,
            event=Taraxa0abciappEvents.DONE,
            destination=Taraxa0abciappStates.MEMECOINPERSONACREATIONROUND.value,
        )

    def setup(self) -> None:
        """Implement the setup."""
        self.context.logger.info("Setting up Taraxa0abciapp FSM behaviour.")

    def teardown(self) -> None:
        """Implement the teardown."""
        self.context.logger.info("Tearing down Taraxa0abciapp FSM behaviour.")

    def act(self) -> None:
        """Implement the act."""
        super().act()
        if self.current is None:
            self.context.logger.info("No state to act on.")
            self.terminate()

    def terminate(self) -> None:
        """Implement the termination."""
        os._exit(0)
